{% set version = "1.2.12" %}

package:
  name: pylabdd
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pylabdd/pylabdd-{{ version }}.tar.gz
  sha256: 59260a9422a21d8ed8eaf1e3167880d966176587a617b2b3eb29d7511c3d89bd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - libgfortran5                           # [build_platform != target_platform]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - libgfortran5
    - fmodpy
  run:
    - python
    - numpy
    - matplotlib-base
    - fmodpy
    - h5py

test:
  requires:
    - pip
  imports:
    - pylabdd
  commands:
    - pip check

about:
  home: https://github.com/AHartmaier/pyLabDD
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Python Laboratory for Dislocation Dynamics"
  description: |
    pylabdd provides tools for dislocation dynamics simulations in Python,
    including Fortran-accelerated routines via fmodpy.
  dev_url: https://github.com/AHartmaier/pyLabDD

extra:
  recipe-maintainers:
    - AHartmaier
