{% set version = "1.2.3" %}

package:
  name: pylabdd
  version: {{ version }}

source:
  #url: https://pypi.org/packages/source/p/pylabdd/pylabdd-{{ version }}.tar.gz
  #sha256: 6e004a4a18d3e086ce409d75343d0d64d2312901990efa2a1c4987b57597a7a4
  git_url: https://github.com/AHartmaier/pyLabDD.git  # temporary change for test purposes
  git_rev: main
  
build:
  number: 0
  skip: true  # [py>=311]
  skip: true  # [win]
  script: |
    export LIBRARY_PATH="{{ BUILD_PREFIX }}/lib:${LIBRARY_PATH}"
    export DYLD_LIBRARY_PATH="{{ BUILD_PREFIX }}/lib:${DYLD_LIBRARY_PATH}"
    which gfortran; gfortran --version || true
    echo "***FFLAGS=$FFLAGS"
    echo "***LDFLAGS=$LDFLAGS"
    echo "***LIBRARY_PATH=$LIBRARY_PATH"
    ls -l {{ BUILD_PREFIX }}/lib | grep gfortran || true
    if [[ "${CONDA_BUILD_CROSS_COMPILATION:-0}" == "1" ]]; then
        {{ BUILD_PREFIX }}/bin/python -m pip install . -vv --no-deps --no-build-isolation
    else
        {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    fi

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libgfortran5                           # [build_platform != target_platform]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - libgfortran5  
    - fmodpy
  run:
    - python
    - numpy
    - matplotlib-base
    - fmodpy

test:
  requires:
    - pip
  imports:
    - pylabdd
  commands:
    - pip check

about:
  home: https://github.com/AHartmaier/pyLabDD
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Python Laboratory for Dislocation Dynamics"
  description: |
    pylabdd provides tools for dislocation dynamics simulations in Python,
    including Fortran-accelerated routines via fmodpy.
  dev_url: https://github.com/AHartmaier/pyLabDD

extra:
  recipe-maintainers:
    - AHartmaier
